// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using romandent.Models;

#nullable disable

namespace romandent.Migrations
{
    [DbContext(typeof(RomanDentContext))]
    [Migration("20260205010007_TablasIniciales")]
    partial class TablasIniciales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("romandent.Models.Cita", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cita");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCita"));

                    b.Property<int?>("ConsultorioId")
                        .HasColumnType("int")
                        .HasColumnName("consultorio_id");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("creado_por");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("programada")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_hora_fin");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_hora_inicio");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("MotivoConsulta")
                        .HasColumnType("text")
                        .HasColumnName("motivo_consulta");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<int>("OdontologoId")
                        .HasColumnType("int")
                        .HasColumnName("odontologo_id");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int")
                        .HasColumnName("paciente_id");

                    b.Property<DateOnly?>("ProximaCita")
                        .HasColumnType("date")
                        .HasColumnName("proxima_cita");

                    b.Property<string>("TipoCita")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("primera_vez")
                        .HasColumnName("tipo_cita");

                    b.Property<string>("TratamientoRealizado")
                        .HasColumnType("text")
                        .HasColumnName("tratamiento_realizado");

                    b.HasKey("IdCita")
                        .HasName("PK__citas__6AEC3C090E1D7D7C");

                    b.HasIndex("ConsultorioId");

                    b.HasIndex("CreadoPor");

                    b.HasIndex(new[] { "Estado" }, "idx_estado");

                    b.HasIndex(new[] { "FechaHoraInicio" }, "idx_fecha");

                    b.HasIndex(new[] { "OdontologoId" }, "idx_odontologo");

                    b.HasIndex(new[] { "PacienteId" }, "idx_paciente");

                    b.ToTable("citas", (string)null);
                });

            modelBuilder.Entity("romandent.Models.Consultorio", b =>
                {
                    b.Property<int>("IdConsultorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_consultorio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConsultorio"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Equipamiento")
                        .HasColumnType("text")
                        .HasColumnName("equipamiento");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numero");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ubicacion");

                    b.HasKey("IdConsultorio")
                        .HasName("PK__consulto__500D9D3465599F50");

                    b.HasIndex(new[] { "Numero" }, "UQ__consulto__FC77F2115B289899")
                        .IsUnique();

                    b.ToTable("consultorios", (string)null);
                });

            modelBuilder.Entity("romandent.Models.EspecialidadesOdontologica", b =>
                {
                    b.Property<int>("IdEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_especialidad");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEspecialidad"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<decimal?>("CostoBase")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("costo_base");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int?>("DuracionCitaMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(45)
                        .HasColumnName("duracion_cita_minutos");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEspecialidad")
                        .HasName("PK__especial__C1D13763D3A98C08");

                    b.HasIndex(new[] { "Nombre" }, "UQ__especial__72AFBCC61C4CE363")
                        .IsUnique();

                    b.ToTable("especialidades_odontologicas", (string)null);
                });

            modelBuilder.Entity("romandent.Models.FormasPago", b =>
                {
                    b.Property<int>("IdFormaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_forma_pago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFormaPago"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<decimal?>("ComisionPorcentaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("comision_porcentaje");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<bool?>("RequiereReferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("requiere_referencia");

                    b.HasKey("IdFormaPago")
                        .HasName("PK__formas_p__DA9B39EE7776B052");

                    b.HasIndex(new[] { "Nombre" }, "UQ__formas_p__72AFBCC65C6EF808")
                        .IsUnique();

                    b.ToTable("formas_pago", (string)null);
                });

            modelBuilder.Entity("romandent.Models.Odontologo", b =>
                {
                    b.Property<int>("IdOdontologo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_odontologo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOdontologo"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("ColorAgenda")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("color_agenda");

                    b.Property<decimal?>("ComisionPorcentaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("comision_porcentaje");

                    b.Property<int?>("ConsultorioPrincipalId")
                        .HasColumnType("int")
                        .HasColumnName("consultorio_principal_id");

                    b.Property<string>("DocumentoIdentidad")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("documento_identidad");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("int")
                        .HasColumnName("especialidad_id");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("NumeroColegiatura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("numero_colegiatura");

                    b.Property<decimal?>("TarifaConsulta")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("tarifa_consulta");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdOdontologo")
                        .HasName("PK__odontolo__FBACF3EBFC41AFA1");

                    b.HasIndex("ConsultorioPrincipalId");

                    b.HasIndex(new[] { "DocumentoIdentidad" }, "UQ__odontolo__1A03B13F5FDF3768")
                        .IsUnique()
                        .HasFilter("[documento_identidad] IS NOT NULL");

                    b.HasIndex(new[] { "NumeroColegiatura" }, "UQ__odontolo__D74701062376F6EC")
                        .IsUnique();

                    b.HasIndex(new[] { "EspecialidadId" }, "idx_especialidad");

                    b.ToTable("odontologos", (string)null);
                });

            modelBuilder.Entity("romandent.Models.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_paciente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaciente"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("AlergiasMedicamentos")
                        .HasColumnType("text")
                        .HasColumnName("alergias_medicamentos");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("ContactoEmergenciaNombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contacto_emergencia_nombre");

                    b.Property<string>("ContactoEmergenciaParentesco")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("contacto_emergencia_parentesco");

                    b.Property<string>("ContactoEmergenciaTelefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("contacto_emergencia_telefono");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Distrito")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("distrito");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("documento_identidad");

                    b.Property<int?>("Edad")
                        .HasColumnType("int")
                        .HasColumnName("edad");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("EnfermedadesSistemicas")
                        .HasColumnType("text")
                        .HasColumnName("enfermedades_sistemicas");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("genero");

                    b.Property<string>("NombreSeguro")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_seguro");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("NumeroHistoriaClinica")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("numero_historia_clinica");

                    b.Property<string>("NumeroPoliza")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("numero_poliza");

                    b.Property<string>("PresionArterial")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("presion_arterial");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.Property<bool?>("TieneSeguro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("tiene_seguro");

                    b.Property<string>("TipoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("DNI")
                        .HasColumnName("tipo_documento");

                    b.Property<string>("TipoSangre")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("tipo_sangre");

                    b.Property<string>("TomaMedicamentos")
                        .HasColumnType("text")
                        .HasColumnName("toma_medicamentos");

                    b.Property<DateOnly?>("UltimaVisita")
                        .HasColumnType("date")
                        .HasColumnName("ultima_visita");

                    b.HasKey("IdPaciente")
                        .HasName("PK__paciente__2C2C72BBEB6FF6ED");

                    b.HasIndex(new[] { "DocumentoIdentidad" }, "UQ__paciente__1A03B13F460EF57C")
                        .IsUnique();

                    b.HasIndex(new[] { "NumeroHistoriaClinica" }, "UQ__paciente__AF36E77390726724")
                        .IsUnique()
                        .HasFilter("[numero_historia_clinica] IS NOT NULL");

                    b.HasIndex(new[] { "DocumentoIdentidad" }, "idx_documento");

                    b.HasIndex(new[] { "Nombres", "Apellidos" }, "idx_nombres");

                    b.HasIndex(new[] { "Telefono" }, "idx_telefono");

                    b.ToTable("pacientes", (string)null);
                });

            modelBuilder.Entity("romandent.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<int?>("CitaId")
                        .HasColumnType("int")
                        .HasColumnName("cita_id");

                    b.Property<decimal?>("Descuento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("descuento");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("pendiente")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_pago")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("Igv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("igv");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("numero_comprobante");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int")
                        .HasColumnName("paciente_id");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("razon_social");

                    b.Property<int?>("RegistradoPor")
                        .HasColumnType("int")
                        .HasColumnName("registrado_por");

                    b.Property<string>("Ruc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ruc");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("subtotal");

                    b.Property<string>("TipoComprobante")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("boleta")
                        .HasColumnName("tipo_comprobante");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total");

                    b.HasKey("IdPago")
                        .HasName("PK__pagos__0941B074DAFD3429");

                    b.HasIndex("CitaId");

                    b.HasIndex("RegistradoPor");

                    b.HasIndex(new[] { "NumeroComprobante" }, "UQ__pagos__1850D80D813DF958")
                        .IsUnique()
                        .HasFilter("[numero_comprobante] IS NOT NULL");

                    b.HasIndex(new[] { "Estado" }, "idx_estado_pago");

                    b.HasIndex(new[] { "FechaPago" }, "idx_fecha_pago");

                    b.HasIndex(new[] { "PacienteId" }, "idx_paciente_pago");

                    b.ToTable("pagos", (string)null);
                });

            modelBuilder.Entity("romandent.Models.Tratamiento", b =>
                {
                    b.Property<int>("IdTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tratamiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTratamiento"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("categoria");

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codigo");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("costo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int?>("DuracionMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(45)
                        .HasColumnName("duracion_minutos");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<bool?>("RequiereAnestesia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("requiere_anestesia");

                    b.Property<int?>("SesionesRequeridas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("sesiones_requeridas");

                    b.HasKey("IdTratamiento")
                        .HasName("PK__tratamie__C8825F4C4710718D");

                    b.HasIndex(new[] { "Codigo" }, "UQ__tratamie__40F9A206B6614033")
                        .IsUnique()
                        .HasFilter("[codigo] IS NOT NULL");

                    b.HasIndex(new[] { "Categoria" }, "idx_categoria");

                    b.HasIndex(new[] { "Codigo" }, "idx_codigo");

                    b.ToTable("tratamientos", (string)null);
                });

            modelBuilder.Entity("romandent.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombres")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombres");

                    b.Property<int?>("OdontologoId")
                        .HasColumnType("int")
                        .HasColumnName("odontologo_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("rol");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime")
                        .HasColumnName("ultimo_acceso");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("IdUsuario")
                        .HasName("PK__usuarios__4E3E04AD573868FF");

                    b.HasIndex("OdontologoId");

                    b.HasIndex(new[] { "Username" }, "UQ__usuarios__F3DBC572E12B548A")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "idx_username");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("romandent.Models.Cita", b =>
                {
                    b.HasOne("romandent.Models.Consultorio", "Consultorio")
                        .WithMany("Cita")
                        .HasForeignKey("ConsultorioId")
                        .HasConstraintName("FK__citas__consultor__4E88ABD4");

                    b.HasOne("romandent.Models.Usuario", "CreadoPorNavigation")
                        .WithMany("Cita")
                        .HasForeignKey("CreadoPor")
                        .HasConstraintName("FK__citas__creado_po__4F7CD00D");

                    b.HasOne("romandent.Models.Odontologo", "Odontologo")
                        .WithMany("Cita")
                        .HasForeignKey("OdontologoId")
                        .IsRequired()
                        .HasConstraintName("FK__citas__odontolog__4D94879B");

                    b.HasOne("romandent.Models.Paciente", "Paciente")
                        .WithMany("Cita")
                        .HasForeignKey("PacienteId")
                        .IsRequired()
                        .HasConstraintName("FK__citas__paciente___4CA06362");

                    b.Navigation("Consultorio");

                    b.Navigation("CreadoPorNavigation");

                    b.Navigation("Odontologo");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("romandent.Models.Odontologo", b =>
                {
                    b.HasOne("romandent.Models.Consultorio", "ConsultorioPrincipal")
                        .WithMany("Odontologos")
                        .HasForeignKey("ConsultorioPrincipalId")
                        .HasConstraintName("FK__odontolog__consu__3E52440B");

                    b.HasOne("romandent.Models.EspecialidadesOdontologica", "Especialidad")
                        .WithMany("Odontologos")
                        .HasForeignKey("EspecialidadId")
                        .IsRequired()
                        .HasConstraintName("FK__odontolog__espec__3D5E1FD2");

                    b.Navigation("ConsultorioPrincipal");

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("romandent.Models.Pago", b =>
                {
                    b.HasOne("romandent.Models.Cita", "Cita")
                        .WithMany("Pagos")
                        .HasForeignKey("CitaId")
                        .HasConstraintName("FK__pagos__cita_id__68487DD7");

                    b.HasOne("romandent.Models.Paciente", "Paciente")
                        .WithMany("Pagos")
                        .HasForeignKey("PacienteId")
                        .IsRequired()
                        .HasConstraintName("FK__pagos__paciente___693CA210");

                    b.HasOne("romandent.Models.Usuario", "RegistradoPorNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("RegistradoPor")
                        .HasConstraintName("FK__pagos__registrad__6A30C649");

                    b.Navigation("Cita");

                    b.Navigation("Paciente");

                    b.Navigation("RegistradoPorNavigation");
                });

            modelBuilder.Entity("romandent.Models.Usuario", b =>
                {
                    b.HasOne("romandent.Models.Odontologo", "Odontologo")
                        .WithMany("Usuarios")
                        .HasForeignKey("OdontologoId")
                        .HasConstraintName("FK__usuarios__odonto__44FF419A");

                    b.Navigation("Odontologo");
                });

            modelBuilder.Entity("romandent.Models.Cita", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("romandent.Models.Consultorio", b =>
                {
                    b.Navigation("Cita");

                    b.Navigation("Odontologos");
                });

            modelBuilder.Entity("romandent.Models.EspecialidadesOdontologica", b =>
                {
                    b.Navigation("Odontologos");
                });

            modelBuilder.Entity("romandent.Models.Odontologo", b =>
                {
                    b.Navigation("Cita");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("romandent.Models.Paciente", b =>
                {
                    b.Navigation("Cita");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("romandent.Models.Usuario", b =>
                {
                    b.Navigation("Cita");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
